---
# MAIN REDIS CONFIGUTATION SETTINGS
redis_version: "5.0.5"
redis_url: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
redis_dir: "/opt/redis-{{ redis_version }}"
install_dir: "/opt/"
redis_run_dir: "/var/run/redis"
redis_config_dir: "/etc/redis"
redis_lib_dir: /var/lib/redis
redis_logfile: /var/log/redis.log
redis_port: "6379"
sentinel_port: "26379"
redis_bind_loop: 127.0.0.1
redis_requirepass: password123
redis_master_auth: master
redis_master_name: redis-node-master
# SENTINEL CONFIGURATION SETTINGS
sentinel_requirepass: password123
sentinel_deny_scripts_reconfig: yes
protected_mode: yes
supervised_mode: yes # set to yes or no to allow
sentinel_pid: /var/run/redis-sentinel.pid
sentinel_logfile: /var/log/redis-sentinel.log
sentinel_quorum: 2
sentinel_down_ms: 6000
sentinel_failtime: 6000

# REDIS.CONF SETTINGS
redis_daemon: redis
redis_unixsocket:
redis_timeout: 300
redis_loglevel: "notice"
redis_databases: 16
redis_save:
  - 900 1
  - 300 10
  - 60 10000
redis_rdbcompression: "yes"
redis_dbfilename: dump.rdb
redis_dbdir: /var/lib/redis
redis_maxmemory: 0
redis_maxmemory_policy: "noeviction"
redis_maxmemory_samples: 5
redis_appendonly: "no"
redis_appendfsync: "everysec"
# Add extra include files for local configuration/overrides.
redis_includes: []
# Disable certain Redis commands for security reasons.
redis_disabled_commands: []
#  - FLUSHDB
#  - FLUSHALL
#  - KEYS
#  - PEXPIRE
#  - DEL
#  - CONFIG
#  - SHUTDOWN
#  - BGREWRITEAOF
#  - BGSAVE
#  - SAVE
#  - SPOP
#  - SREM
#  - RENAME
#  - DEBUG
slave_serve_stale_data: "yes"
slave_read_only: "yes"
repl_diskless_sync: "no"
repl_diskless_sync_delay: "5"
repl_disable_tcp_nodelay: "no"
slave_priority: "100"
lazyfree_lazy_eviction: "no"
lazyfree_lazy_expire: "no"
lazyfree_lazy_server_del: "no"
slave_lazy_flush: "no"
appendonly: "no"
appendfilename: "appendonly.aof"
appendfsync1: always
appendfsync2: ""
appendfsync3: ""
no_appendfsync_on_rewrite: "no"
auto_aof_rewrite_percentage: "100"
auto_aof_rewrite_min_size: "64mb"
aof_load_truncated: "yes"
aof_use_rdb_preamble: "no"
lua_time_limit: "5000"
slowlog_log_slower_than: "10000"
slowlog_max_len: "128"
latency_monitor_threshold: "0"
notify_keyspace_events: ""
hash_max_ziplist_entries: "512"
hash_max_ziplist_value: "64"
list_max_ziplist_size: "_2"
list_compress_depth: "0"
set_max_intset_entries: "512"
zset_max_ziplist_entries: "128"
zset_max_ziplist_value: "64"
hll_sparse_max_bytes: "3000"
activerehashing: "yes"
client_output_buffer_limit1: "normal 0 0 0"
client_output_buffer_limit2: "slave 256mb 64mb 60"
client_output_buffer_limit3: "pubsub 32mb 8mb 60"
hz: "10"
aof_rewrite_incremental_fsync: "yes"
