- hosts: redis-nodes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    # Include variables and define needed variables.
    - name: Include vars
      include_vars:
        file: group_vars/all.yml
    - import_tasks: "{{ playbook_dir }}/tasks/setup_requirements.yml"
    - import_tasks: "{{ playbook_dir }}/tasks/1.epel_install.yml"
      when: epel_install is defined
    - import_tasks: "{{ playbook_dir }}/tasks/1.latest_install.yml"
      when: manual_install is defined
    - import_tasks: "{{ playbook_dir }}/tasks/2.copy.yml"
    - import_tasks: "{{ playbook_dir }}/tasks/3.firewall.yml"
    - import_tasks: "{{ playbook_dir }}/tasks/4.systemd.yml"
    - import_tasks: "{{ playbook_dir }}/tasks/5.start.yml"
