---
- name: build list of Redis Masters
  vars:
    data_yaml: |
      #!jinja2: lstrip_blocks: True
      {% for host in groups['redis-nodes'] %}
        {% if hostvars[host]['redis_role'] == 'master' %}
        - {{ hostvars[host]['ansible_default_ipv4']['address'] }}
        {% endif %}
      {% endfor %}
  set_fact:
    redis_masters: "{{ data_yaml | from_yaml }}"

- name: build list of Redis Slaves
  vars:
    data_yaml: |
      #!jinja2: lstrip_blocks: True
      {% for host in groups['redis-nodes'] %}
        {% if hostvars[host]['redis_role'] == 'slave' %}
        - {{ hostvars[host]['ansible_default_ipv4']['address'] }}
        {% endif %}
      {% endfor %}
  set_fact:
    redis_slaves: "{{ data_yaml | from_yaml }}"

- name: build list of Redis Sentinels
  vars:
    data_yaml: |
      #!jinja2: lstrip_blocks: True
      {% for host in groups['redis-nodes'] %}
        {% if hostvars[host]['redis_role'] == 'sentinel' %}
        - {{ hostvars[host]['ansible_default_ipv4']['address'] }}
        {% endif %}
      {% endfor %}
  set_fact:
    redis_sentinels: "{{ data_yaml | from_yaml }}"

- debug:
    msg: "Redis master {{ redis_masters }}"
- debug:
    msg: "Redis slaves {{ redis_slaves }}"
- debug:
    msg: "Redis sentinels {{ redis_sentinels }}"

- name: Create Redis dir's
  file:
   path: "{{item}}"
   state: directory
   mode: 0755
  with_items:
    - "{{ redis_config_dir }}"
    - "{{ redis_run_dir }}"
  become: true

- name: Create Redis LOG DIR
  file:
   path: "{{item}}"
   state: touch
   mode: 0755
  with_items:
    - "{{ redis_logfile }}"
    - "{{ sentinel_logfile }}"
  become: true

# Fix overcommit_memory warnings
- name: overcommit_memory warnings Fix
  command: "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf"
  become: true

# Fix for  Transparent Huge Pages (THP) support in kernet
- name: Transparent Huge Pages Fix
  command: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
  become: true
