---
- name: Add Epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install Redis
  yum:
    name: redis
    state: present
  become: true
