---
- name: Install dependancies
  package:
    name: [cmake, tcl]
    state: present
  become: true

- name: Download and Extract Redis {{ redis_version }}
  unarchive:
    src: "{{ redis_url }}"
    dest: "{{ install_dir }}"
    remote_src: yes
  become: true

- name: copy redis-server to /usr/local/bin/
  copy:
    src: "{{ redis_dir }}/src/redis-server"
    dest: /usr/local/bin/
    remote_src: yes
  become: true

- name: copy redis-cli to /usr/local/bin/
  copy:
    src: "{{ redis_dir }}/src/redis-cli"
    dest: /usr/local/bin/
    remote_src: yes
  become: true

- name: run make install
  command: "sudo make"
  become: true
  args:
    chdir: "{{ redis_dir }}"
