---
- name: Download Redis {{ redis_version }}
  get_url:
    url: "{{ redis-url }}"
    dest: "{{ install_dir }}"

#- name: Download and Extract Redis {{ redis_version }}
#  unarchive:
#    src: "{{ redis_url }}"
#    dest: "{{ install_dir }}"
#    remote_src: yes

- name: create redis run dir
  file:
    path: /var/run/redis
    state: directory
    group: root
    owner: root

- name: sudo make
  command: "sudo make"
  args:
    chdir: "{{ redis_dir }}"
