---
<<<<<<< HEAD
=======
#- name: Download Redis {{ redis_version }}
#  get_url:
#    url: "{{ redis_url }}"
#    dest: "{{ install_dir }}"

>>>>>>> 5abf557ed7b3a618225e64d7e055bf81d5d199f3
- name: Download and Extract Redis {{ redis_version }}
  unarchive:
    src: "{{ redis_url }}"
    dest: "{{ install_dir }}"
    remote_src: yes

- name: create redis run dir
  file:
    path: /var/run/redis
    state: directory
    group: root
    owner: root

- name: sudo make test
  command: "make test"
  become: yes
  args:
    chdir: "{{ redis_dir }}/src/"

- name: sudo make install
  command: "make"
  become: yes
  args:
    chdir: "{{ redis_dir }}/src/"
