---
- name: Create Redis dir's
  file:
   path: "{{item}}"
   state: directory
   mode: 0755
  with_items:
    - "{{ redis_config_dir }}"
    - "{{ redis_run_dir }}"
    - "{{ redis_lib_dir }}"
  become: true

- name: Create Redis LOG DIR
  file:
   path: "{{item}}"
   state: touch
   mode: 0755
  with_items:
    - "{{ redis_logfile }}"
    - "{{ sentinel_logfile }}"
  become: true

- name: Overcommit_memory warnings Fix
  lineinfile:
    path: "/etc/sysctl.conf"
    line: "vm.overcommit_memory = 1"
  become: true

# Fix Transparent Huge Pages warnings
#- name: Transparent Huge Pages Fix
#  lineinfile:
#    path: "/sys/kernel/mm/transparent_hugepage/enabled"
#    line: "never"
#  become: true

- name: Download and Extract Redis {{ redis_version }}
  unarchive:
    src: "{{ redis_url }}"
    dest: "{{ install_dir }}"
    remote_src: yes
  become: true

#- name: run make test
#  command: "sudo make test"
#  become: true
#  ignore_errors: True
#  args:
#    chdir: "{{ redis_dir }}/src/"

- name: Run 'make install' target as root
  make:
    chdir: "{{ redis_dir }}/src/"
    target: install
  become: true

- name: Run 'make install' target as root
  make:
    chdir: "{{ redis_dir }}/src/"
    target: install
  become: true

- name: copy redis-server to /usr/local/bin/
  copy:
    src: "{{ redis_dir }}/src/redis-server"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes
  become: true
  ignore_errors: True

- name: copy redis-cli to /usr/local/bin/
  copy:
    src: "{{ redis_dir }}/src/redis-cli"
    dest: /usr/local/bin/
    remote_src: yes
    mode: 0755
  become: true
  ignore_errors: True
