---
- name: Download and Extract Redis {{ redis_version }}
  unarchive:
    src: "{{ redis_url }}"
    dest: "{{ install_dir }}"
    remote_src: yes
  become: true

- name: create redis run dir
  file:
    path: /var/run/redis
    state: directory
    group: root
    owner: root
  become: true

- name: sudo make test
  command: "sudo make test"
  args:
    chdir: "{{ redis_dir }}/src/"
  register: install_test
  become: true

- name: sudo make install
  command: "make"
  become: yes
  args:
    chdir: "{{ redis_dir }}/src/"
  when: install_test is succeeded
  become: true
