---
- name: Define redis_cache.
  set_fact:
    redis_cache: "{{ __redis_cache }}"
  when: redis_cache is not defined

- name: Define redis_session.
  set_fact:
    redis_session: "{{ __redis_session }}"
  when: redis_session is not defined

- name: Install dependancies
  package:
    name: [cmake, tcl]
    state: present
  become: true

- name: Install Python dependancies
  pip:
    name: netaddr

- name: Get list of Redis Masters
  vars:
    data_yaml: |
      #!jinja2: lstrip_blocks: True
      {% for host in groups['redis-nodes'] %}
        {% if hostvars[host]['redis_role'] == 'master' %}
        - {{ hostvars[host]['ansible_default_ipv4']['address'] }}
        {% endif %}
      {% endfor %}
  set_fact:
    # Its ugly but this eliminates white spaces adn new lines to format the given value into the redis conf files correctly
    redis_masters: "{{ data_yaml | from_yaml | to_nice_yaml | regex_replace('-','') | regex_replace('\n','') | regex_replace('^\\/', '') }}"
