---
#- debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
#  register: redis_master_ip

#- debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
#  register: redis_slave_ip

 #COPY PORT 1 FILES
- name: Copy redis master conf
  template:
    src: master-conf.j2
    dest: "/etc/redis/redis.conf"
  when: "redis-role == 'master'"
  when: "{{ hostvars['redis-role'].master }}"
#  when: "redis_masters is defined and redis-role == 'master"
  become: true

- name: Copy Redis slave conf
  template:
    src: slave-conf.j2
    dest: "/etc/redis/redis.conf"
  when: "redis-role == 'slave'"
#  when: redis_slaves is defined
  become: true

 #COPY PORT 2 FILES
- name: Copy Redis-Sentinel slave conf
  template:
    src: sentinel.j2
    dest: "/etc/redis/sentinel.conf"
  become: true
