---
 #COPY MASTER CONF
- name: Copy redis master conf
  template:
    src: master-conf.j2
    dest: "/etc/redis/redis.conf"
  become: true
  when: redis_role == "master"
  
 #COPY SLAVE CONF
- name: Copy Redis slave conf
  template:
    src: slave-conf.j2
    dest: "/etc/redis/redis.conf"
  become: true
  when: redis_role == "slave"

 #COPY SENTINEL CONF
- name: Copy Redis-Sentinel conf
  template:
    src: sentinel.j2
    dest: "/etc/redis/sentinel.conf"
  become: true
  when: redis_role == "sentinel"
