---
- debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
  register: redis_parent_ip

- debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
  register: redis_child_ip
  
 #COPY PORT 1 FILES
- name: Copy redis Parent conf
  template:
    src: parent-conf.j2
    dest: "/etc/redis/redis.conf"
  when: "inventory_hostname in groups['redis']"
#  when: "inventory_hostname in groups['redis'] and redis_cluster == parent"

- name: Copy Redis Child conf
  template:
    src: child-conf.j2
    dest: "/etc/redis/redis.conf"
  when: "inventory_hostname in groups['redis']"
#  when: "inventory_hostname in groups['redis'] and redis_cluster == child"

 #COPY PORT 2 FILES
- name: Copy Redis-Sentinel Child conf
  template:
    src: sentinel.j2
    dest: "/etc/redis/sentinel.conf"
  when: "inventory_hostname in groups['sentinel'] or inventory_hostname in groups['redis']"
#  when: "inventory_hostname in groups['redis-ha'] and redis_cluster=child"

#alternative method to copying files in redis setup
- name: Copy Redis conf
  copy:
    src: "{{ playbook_dir }}/templates/{{ env }}/redis.conf"
    dest: "/etc/redis/redis.conf"
    remote_src: no
    owner: root

- name: Copy Sentinel Conf
  copy:
  copy:
    src: "{{ playbook_dir }}/templates/{{ env }}/sentinel.conf"
    dest: "/etc/redis/sentinel.conf"
    remote_src: no
    owner: root
