---

 #COPY MASTER CONF
- name: Copy /etc/redis/redis.conf template
  template:
    src: "{{ redis_role }}-conf.j2"
    dest: "/etc/redis/redis.conf"
    mode: 0644
  become: true
#  when: redis_role == "master" or

 #COPY SENTINEL CONF
- name: Copy /etc/redis/sentinel.conf  template
  template:
    src: "sentinel.j2"
    dest: "/etc/redis/sentinel.conf"
    mode: 0644
  become: true
