---
- debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
  register: redis_master_ip

- debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
  register: redis_slave_ip
  
 #COPY PORT 1 FILES
- name: Copy redis master conf
  template:
    src: master-conf.j2
    dest: "/etc/redis/redis.conf"
  when: "inventory_hostname in groups['redis']"
#  when: "inventory_hostname in groups['redis'] and redis-role == master"

- name: Copy Redis slave conf
  template:
    src: slave-conf.j2
    dest: "/etc/redis/redis.conf"
  when: "inventory_hostname in groups['redis']"
#  when: "inventory_hostname in groups['redis'] and redis-role == slave"

 #COPY PORT 2 FILES
- name: Copy Redis-Sentinel slave conf
  template:
    src: sentinel.j2
    dest: "/etc/redis/sentinel.conf"
  when: "inventory_hostname in groups['sentinel'] or inventory_hostname in groups['redis']"
#  when: "inventory_hostname in groups['redis-ha'] and redis-role=slave"

#alternative method to copying files in redis setup
- name: Copy Redis conf
  copy:
    src: "{{ playbook_dir }}/templates/{{ env }}/redis.conf"
    dest: "/etc/redis/redis.conf"
    remote_src: no
    owner: root

- name: Copy Sentinel Conf
  copy:
  copy:
    src: "{{ playbook_dir }}/templates/{{ env }}/sentinel.conf"
    dest: "/etc/redis/sentinel.conf"
    remote_src: no
    owner: root
