- name: Add TCP PORT {{ redis_port }}
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: "{{ redis_port }}"

- name: Add TCP PORT {{ sentinel_port }}
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: "{{ sentinel_port }}"

- name: Add TCP PORT {{ redis_port }}
  firewalld:
   port: "{{ redis_port }}/tcp"
   zone: public
   permanent: true
   state: enabled

- name: Add TCP PORT {{ sentinel_port }}
  firewalld:
   port: "{{ sentinel_port }}/tcp"
   zone: public
   permanent: true
   state: enabled
