- name: Add TCP PORT {{ redis_port }}
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: "{{ redis_port }}"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 6

- name: Add TCP PORT {{ sentinel_port }}
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: "{{ sentinel_port }}"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 6

- name: ADD FIREWALLD TCP PORT {{ redis_port }}
  firewalld:
   port: "{{ redis_port }}/tcp"
   zone: public
   permanent: true
   state: enabled
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7

- name: ADD FIREWALLD TCP PORT {{ sentinel_port }}
  firewalld:
   port: "{{ sentinel_port }}/tcp"
   zone: public
   permanent: true
   state: enabled
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7
