- name: Add TCP PORT {{ redis_port }}
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: "{{ redis_port }}"
  when: "memcached_port is defined and ansible_distribution == 'RedHat'"

- name: Add TCP PORT {{ sentinel_port }}
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: "{{ sentinel_port }}"
  when: "memcached_port is defined and ansible_distribution == 'RedHat'"

- name: Add TCP PORT {{ redis_port }}
  firewalld:
   port: "{{ redis_port }}/tcp"
   zone: public
   permanent: true
   state: enabled
  when: "memcached_port is defined and ansible_distribution == 'CentOS'"

- name: Add TCP PORT {{ sentinel_port }}
  firewalld:
   port: "{{ sentinel_port }}/tcp"
   zone: public
   permanent: true
   state: enabled
  when: "memcached_port2 is defined and ansible_distribution == 'CentOS'"
