---
- name: Start Redis
  systemd:
    name: redis
    state: started
  become: true
  when: redis_role != "sentinel"

- name: Start Redis Sentinel
  systemd:
    name: redis-sentinel
    state: started
  become: true
