---
- name: Download and Install Redis {{ redis-version }}
  unarchive:
    src: "{{ redis-url }}"
    dest: "{{ install_dir }}"
    remote_src: yes

- name: Install {{ redis_version }}
  command: "sudo sh configure --prefix={{ redis_dir }}/"
  args:
    chdir: "{{ install_dir }}"
  register: config_mem

- name: sudo make
  command: "sudo make"
  args:
    chdir: "{{ install_dir }}"
  register: config_mem

- name: sudo make install
  command: "sudo make install"
  args:
    chdir: "{{ install_dir }}"
  register: config_mem

- debug: msg="{{ config_mem.stdout }}"


- name: Copy Redis conf
  copy:
    src: "{{ playbook_dir }}/templates/{{ env }}/redis.conf"
    dest: "/etc/redis/redis.conf"
    remote_src: no
    owner: root

- name: Copy Sentinel Conf
  copy:
  copy:
    src: "{{ playbook_dir }}/templates/{{ env }}/sentinel.conf"
    dest: "/etc/redis/sentinel.conf"
    remote_src: no
    owner: root

- name: create redis run dir
  file:
    path: /var/run/redis
    state: directory
    group: root
    owner: root
