---
- name: Copy and configure Redis systemd service
  copy:
    src: "{{ playbook_dir }}/templates/{{ env }}/service/redis.service"
    dest: "/etc/systemd/system/redis.service"
    remote_src: no

- name: Copy and configure Redis-Sentinel systemd service
  copy:
    src: "{{ playbook_dir }}/templates/{{ env }}/service/redis-sentinel.service"
    dest: "/etc/systemd/system/redis-sentinel.service"
    remote_src: no
    owner: root

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable Redis on boot
  systemd:
    name: redis
    state: enable

- name: Enable Redis-sentinel on boot
  systemd:
    name: redis-sentinel
    state: enabled
